"""Tables

Revision ID: c3daaf62cf6c
Revises: 
Create Date: 2021-07-14 08:54:48.372490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3daaf62cf6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('flag', sa.Text(), nullable=False),
    sa.Column('flagPath', sa.String(length=256), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('flag'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolName', sa.Text(), nullable=False),
    sa.Column('appForm', sa.Text(), nullable=True),
    sa.Column('appFormsPath', sa.String(length=256), nullable=True),
    sa.Column('feesForm', sa.Text(), nullable=True),
    sa.Column('feesFormsPath', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appForm'),
    sa.UniqueConstraint('feesForm')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolName', sa.Text(), nullable=False),
    sa.Column('schoolPix', sa.Text(), nullable=False),
    sa.Column('schoolPixPath', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=False),
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=40), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('imagePath', sa.String(length=256), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('excerpt'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('title')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colour1', sa.String(length=7), nullable=False),
    sa.Column('colour2', sa.String(length=7), nullable=False),
    sa.Column('schoolName', sa.String(length=100), nullable=False),
    sa.Column('schoolType', sa.String(length=6), nullable=False),
    sa.Column('population', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=60), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('logo', sa.Text(), nullable=False),
    sa.Column('logoPath', sa.String(length=256), nullable=False),
    sa.Column('badge', sa.Text(), nullable=False),
    sa.Column('badgePath', sa.String(length=256), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=35), nullable=False),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.Column('academics', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('care', sa.Text(), nullable=True),
    sa.Column('newHeading', sa.Text(), nullable=True),
    sa.Column('newBody', sa.Text(), nullable=True),
    sa.Column('newHeading2', sa.Text(), nullable=True),
    sa.Column('newBody2', sa.Text(), nullable=True),
    sa.Column('newHeading3', sa.Text(), nullable=True),
    sa.Column('newBody3', sa.Text(), nullable=True),
    sa.Column('link1', sa.String(length=256), nullable=True),
    sa.Column('link2', sa.String(length=256), nullable=True),
    sa.Column('link3', sa.String(length=256), nullable=True),
    sa.Column('link4', sa.String(length=256), nullable=True),
    sa.Column('link5', sa.String(length=256), nullable=True),
    sa.Column('tour', sa.String(length=256), nullable=True),
    sa.Column('appLink', sa.String(length=256), nullable=True),
    sa.Column('feesLink', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('schoolName')
    )
    op.create_table('thumbnails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('vidPix', sa.Text(), nullable=False),
    sa.Column('vidPixPath', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firstName'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('thumbnails')
    op.drop_table('schools')
    op.drop_table('news')
    op.drop_table('images')
    op.drop_table('documents')
    op.drop_table('country')
    # ### end Alembic commands ###
